kindling.module(function () {
	'use strict';
	
	var MENU_ID = 'emojiButton-wrapper';

	function insertAtCaret(input, value) {
		if (input.selectionStart || input.selectionStart === 0) {
			input.value = input.value.substring(0, input.selectionStart) + value + input.value.substring(input.selectionEnd, input.value.length);
			input.selectionStart = input.selectionEnd = input.selectionStart + value.length;
		} else {
			input.value += value;
		}
	}

	function displayMenu() {
		if (document.getElementById(MENU_ID)) {
			return;
		}

		var $menu = $('<div id="' + MENU_ID + '" class="tooltip">\
				<img id="emojiButton" title="' + chrome.i18n.getMessage('emojiMenuTooltip') + '" src="' + chrome.extension.getURL('img/emoji.gif') + '" width="16" height="16"/>\
				<div id="emojiContainer" class="tooltip-inner">\
					<div id="emoji-slider" class="coda-slider"></div>\
					<div id="coda-nav-1" class="coda-nav">\
						<ul>\
							<li class="tab1"><a class="tab-button" href="#"><img height="16" width="16" src="' + chrome.extension.getURL('img/emoji.gif') + '"/></a></li>\
							<li class="tab2"><a class="tab-button" href="#"><img height="16" width="16" src="' + chrome.extension.getURL('img/nature.png') + '"/></a></li>\
							<li class="tab3"><a class="tab-button" href="#"><img height="16" width="16" src="' + chrome.extension.getURL('img/objects.png') + '"/></a></li>\
							<li class="tab4"><a class="tab-button" href="#"><img height="16" width="16" src="' + chrome.extension.getURL('img/places.png') + '"/></a></li>\
							<li class="tab5"><a class="tab-button" href="#"><img height="16" width="16" src="' + chrome.extension.getURL('img/symbols.png') + '"/></a></li>\
						</ul>\
					</div>\
				</div>\
		</div>');

		var $emojiContainer = $menu.find('#emojiContainer');
		var $emojiSlider = $emojiContainer.find('#emoji-slider');
		var i;
		for (var group in EMOJIS) {
			var $panel = $('<div class="panel"><div class="panel-wrapper"></div></div>');
			var $wrapper = $panel.find('.panel-wrapper');
			for (i = 0; i < EMOJIS[group].length; i++) {
				$wrapper.append('<span class="emoji emoji-' + EMOJIS[group][i] + '" title="' + EMOJIS[group][i] + '"></span>');
			}
			$emojiSlider.append($panel);
		}

		$('#chat_controls').append($menu);
		
		$('#emoji-slider').codaSlider();

		$(document).click(function (e) {
			if (e.target.id === 'emojiButton') {
				$emojiContainer.toggle();
			} else if ($menu.find(e.target).length) {
				e.preventDefault();
			} else {
				$emojiContainer.hide();
			}
		});

		var $input = $('#input');
		$emojiContainer.click(function (e) {
			if ($(e.target).hasClass('emoji')) { 
				insertAtCaret($input[0], ':' + e.target.getAttribute('title') + ':');
				$input.focus();
			}
		});
	}

	function onOptionsChanged(e, options) {
		if (options.soundAndEmojiMenus === 'true') {
			displayMenu();
		} else {
			$('#' + MENU_ID).remove();
		}
	}

	// List gathered from http://www.emoji-cheat-sheet.com
	var EMOJIS = { 
	'people': [
		'smile',
		'blush',
		'smiley',
		'relaxed',
		'smirk',
		'heart_eyes',
		'kissing_heart',
		'kissing_face',
		'flushed',
		'relieved',
		'satisfied',
		'grin',
		'wink',
		'wink2',
		'tongue',
		'unamused',
		'sweat',
		'pensive',
		'disappointed',
		'confounded',
		'fearful',
		'cold_sweat',
		'persevere',
		'cry',
		'sob',
		'joy',
		'astonished',
		'scream',
		'angry',
		'rage',
		'sleepy',
		'mask',
		'bowtie',
		'imp',
		'alien',
		'yellow_heart',
		'blue_heart',
		'purple_heart',
		'heart',
		'green_heart',
		'broken_heart',
		'heartbeat',
		'heartpulse',
		'cupid',
		'sparkles',
		'star',
		'star2',
		'anger',
		'exclamation',
		'question',
		'grey_exclamation',
		'grey_question',
		'zzz',
		'dash',
		'sweat_drops',
		'notes',
		'musical_note',
		'fire',
		'poop',
		'thumbsup',
		'thumbsdown',
		'ok_hand',
		'punch',
		'fist',
		'v',
		'wave',
		'hand',
		'open_hands',
		'point_up',
		'point_up_2',
		'point_down',
		'point_left',
		'point_right',
		'raised_hands',
		'pray',
		'clap',
		'muscle',
		'metal',
		'walking',
		'runner',
		'couple',
		'dancer',
		'dancers',
		'bow',
		'ok_woman',
		'no_good',
		'information_desk_person',
		'couplekiss',
		'couple_with_heart',
		'massage',
		'haircut',
		'nail_care',
		'boy',
		'girl',
		'woman',
		'man',
		'baby',
		'older_woman',
		'older_man',
		'person_with_blond_hair',
		'man_with_gua_pi_mao',
		'man_with_turban',
		'construction_worker',
		'cop',
		'angel',
		'princess',
		'guardsman',
		'skull',
		'feet',
		'lips',
		'kiss',
		'ear',
		'eyes',
		'nose',
		'suspect',
		'rage1',
		'rage2',
		'rage3',
		'rage4',
		'hurtrealbad',
		'goberserk',
		'feelsgood',
		'finnadie',	
		'godmode',
		'trollface',
		'shipit',
		'octocat',
	],
	'nature': [
		'sunny',
		'umbrella',
		'cloud',
		'snowman',
		'moon',
		'zap',
		'cyclone',
		'ocean',
		'cat',
		'dog',
		'mouse',
		'hamster',
		'rabbit',
		'wolf',
		'frog',
		'tiger',
		'koala',
		'bear',
		'pig',
		'cow',
		'boar',
		'monkey_face',
		'monkey',
		'horse',
		'racehorse',
		'camel',
		'sheep',
		'elephant',
		'snake',
		'bird',
		'baby_chick',
		'chicken',
		'penguin',
		'bug',
		'octopus',
		'tropical_fish',
		'fish',
		'whale',
		'dolphin',
		'bouquet',
		'cherry_blossom',
		'tulip',
		'four_leaf_clover',
		'rose',
		'sunflower',
		'hibiscus',
		'maple_leaf',
		'leaves',
		'fallen_leaf',
		'palm_tree',
		'cactus',
		'ear_of_rice',
		'shell'
	],
	'objects': [
		'bamboo',
		'gift_heart',
		'dolls',
		'school_satchel',
		'mortar_board',
		'flags',
		'fireworks',
		'sparkler',
		'wind_chime',
		'rice_scene',
		'jack_o_lantern',
		'ghost',
		'santa',
		'christmas_tree',
		'gift',
		'bell',
		'tada',
		'balloon',
		'cd',
		'dvd',
		'camera',
		'movie_camera',
		'computer',
		'tv',
		'iphone',
		'fax',
		'phone',
		'minidisc',
		'vhs',
		'speaker',
		'loudspeaker',
		'mega',
		'radio',
		'satellite',
		'loop',
		'mag',
		'unlock',
		'lock',
		'key',
		'scissors',
		'hammer',
		'bulb',
		'calling',
		'email',
		'mailbox',
		'postbox',
		'bath',
		'toilet',
		'seat',
		'moneybag',
		'trident',
		'smoking',
		'bomb',
		'gun',
		'pill',
		'syringe',
		'football',
		'basketball',
		'soccer',
		'baseball',
		'tennis',
		'golf',
		'8ball',
		'swimmer',
		'surfer',
		'ski',
		'spades',
		'hearts',
		'clubs',
		'diamonds',
		'gem',
		'ring',
		'trophy',
		'space_invader',
		'dart',
		'mahjong',
		'clapper',
		'memo',
		'book',
		'art',
		'microphone',
		'headphones',
		'trumpet',
		'saxophone',
		'guitar',
		'part_alternation_mark',
		'shoe',
		'sandal',
		'high_heel',
		'lipstick',
		'boot',
		'shirt',
		'necktie',
		'dress',
		'kimono',
		'bikini',
		'ribbon',
		'tophat',
		'crown',
		'womans_hat',
		'closed_umbrella',
		'briefcase',
		'handbag',
		'beer',
		'beers',
		'cocktail',
		'sake',
		'fork_and_knife',
		'hamburger',
		'fries',
		'spaghetti',
		'curry',
		'bento',
		'sushi',
		'rice_ball',
		'rice_cracker',
		'rice',
		'ramen',
		'stew',
		'bread',
		'egg',
		'oden',
		'dango',
		'icecream',
		'shaved_ice',
		'birthday',
		'cake',
		'apple',
		'tangerine',
		'watermelon',
		'strawberry',
		'eggplant',
		'tomato',
		'coffee',
		'tea'
	],
	'places': [
		'house',
		'school',
		'office',
		'post_office',
		'hospital',
		'bank',
		'convenience_store',
		'love_hotel',
		'hotel',
		'wedding',
		'church',
		'department_store',
		'109',
		'city_sunrise',
		'city_sunset',
		'japanese_castle',
		'european_castle',
		'tent',
		'factory',
		'tokyo_tower',
		'mount_fuji',
		'sunrise_over_mountains',
		'sunrise',
		'stars',
		'statue_of_liberty',
		'rainbow',
		'ferris_wheel',
		'fountain',
		'roller_coaster',
		'ship',
		'speedboat',
		'boat',
		'sailboat',
		'airplane',
		'rocket',
		'bike',
		'blue_car',
		'car',
		'taxi',
		'bus',
		'police_car',
		'fire_engine',
		'ambulance',
		'truck',
		'train',
		'station',
		'bullettrain_front',
		'bullettrain_side',
		'ticket',
		'fuelpump',
		'traffic_light',
		'warning',
		'construction',
		'beginner',
		'atm',
		'slot_machine',
		'busstop',
		'barber',
		'hotsprings',
		'checkered_flag',
		'crossed_flags',
		'jp',
		'kr',
		'cn',
		'us',
		'fr',
		'es',
		'it',
		'ru',
		'gb',
		'de'
	],
	'symbols': [
		'1',
		'2',
		'3',
		'4',
		'5',
		'6',
		'7',
		'8',
		'9',
		'0',
		'hash',
		'arrow_backward',
		'arrow_down',
		'arrow_forward',
		'arrow_left',
		'arrow_lower_left',
		'arrow_lower_right',
		'arrow_right',
		'arrow_up',
		'arrow_upper_left',
		'arrow_upper_right',
		'rewind',
		'fast_forward',
		'ok',
		'new',
		'top',
		'up',
		'cool',
		'cinema',
		'koko',
		'signal_strength',
		'u5272',
		'u55b6',
		'u6307',
		'u6708',
		'u6709',
		'u6e80',
		'u7121',
		'u7533',
		'u7a7a',
		'sa',
		'restroom',
		'mens',
		'womens',
		'baby_symbol',
		'no_smoking',
		'parking',
		'wheelchair',
		'metro',
		'wc',
		'secret',
		'congratulations',
		'ideograph_advantage',
		'underage',
		'id',
		'eight_spoked_asterisk',
		'eight_pointed_black_star',
		'heart_decoration',
		'vs',
		'vibration_mode',
		'mobile_phone_off',
		'chart',
		'currency_exchange',
		'aries',
		'taurus',
		'gemini',
		'cancer',
		'leo',
		'virgo',
		'libra',
		'scorpius',
		'sagittarius',
		'capricorn',
		'aquarius',
		'pisces',
		'ophiuchus',
		'six_pointed_star',
		'a',
		'b',
		'ab',
		'o2',
		'red_circle',
		'black_square',
		'white_square',
		'clock1',
		'clock10',
		'clock11',
		'clock12',
		'clock2',
		'clock3',
		'clock4',
		'clock5',
		'clock6',
		'clock7',
		'clock8',
		'clock9',
		'o',
		'x',
		'copyright',
		'registered',
		'tm'
	]};

	return {
		init: function () {
			$.subscribe('optionsChanged', onOptionsChanged);
		}
	};
}());
